// Contenu — partie 3 : chapitre IV, conclusion générale, bibliographie
const L = require('./lib');
const { P, bullets, numbered, H2, H3, H4, chapter, partPage, T, figure, setChapter, note, code } = L;
const { Paragraph, TextRun, AlignmentType } = L.d;
const CEN = AlignmentType.CENTER;

const cap = (f, c) => figure(`memoire/captures/${f}`, c, { maxW: 600 });

function chapitre4() {
  setChapter(4);
  return [
    ...partPage('Partie III', 'Développement', 'La réalisation'),
    ...chapter('Chapitre IV', 'La réalisation'),
    H2('1. Introduction'),
    P("Ce chapitre présente la mise en œuvre de la conception : l'architecture de la solution, les langages et logiciels utilisés, l'implémentation de la base de données, les principales interfaces, les mesures de sécurité, l'hébergement, puis les tests et la recette."),

    H2('2. Solution informatique'),
    H3('2.1 Architecture de la solution'),
    P("La solution adopte une architecture **trois tiers** de type client-serveur :"),
    ...bullets([
      "**Couche présentation** : l'application web Vue.js (SPA), exécutée dans le navigateur, qui consomme l'API.",
      "**Couche métier** : une API REST Laravel organisée selon le patron MVC (routes, contrôleurs, modèles, middlewares, service de passage de semestre).",
      "**Couche données** : une base de données MySQL, accédée via l'ORM Eloquent ; les fichiers (cours, documents, remises) sont stockés sur le disque du serveur.",
    ]),
    ...figure('memoire/uml/architecture.png', 'Architecture trois tiers de la solution'),
    P("L'application web s'authentifie par **session et cookie httpOnly** (Laravel Sanctum en mode SPA), ce qui évite d'exposer un jeton au code JavaScript. L'assistant intelligent interroge l'API Gemini depuis le serveur."),
    H3('2.2 Les langages de programmation et les logiciels utilisés'),
    H4('2.2.1 Les langages de programmation'),
    ...T('Langages et frameworks', ['Langage / framework', 'Version', 'Utilisation'], [
      ['PHP / Laravel', 'PHP 8.3 / Laravel 12', "API REST : routes, contrôleurs, validation, ORM Eloquent, migrations, Sanctum"],
      ['JavaScript / Vue.js', 'Vue 3.4 (Vite 5)', 'Application web SPA : vues, routeur, état (Pinia), appels HTTP (Axios)'],
      ['CSS / Tailwind CSS', 'Tailwind 3.4', 'Mise en forme, thème clair / sombre, responsive'],
      ['SQL / MySQL', 'MySQL 8.4', 'Stockage des données'],
      ['HTML', 'HTML5', 'Structure des pages'],
    ], [26, 22, 52]),
    H4('2.2.2 Les logiciels'),
    ...T('Logiciels et outils', ['Logiciel / outil', 'Utilisation'], [
      ['Visual Studio Code', 'Éditeur de code'],
      ['Laragon', 'Environnement local (PHP, MySQL, serveur web)'],
      ['Composer / npm', 'Gestion des dépendances PHP et JavaScript'],
      ['Vite', 'Serveur de développement et construction du frontend'],
      ['Git / GitHub', 'Gestion des versions et historique du projet'],
      ['Chart.js', 'Graphiques des tableaux de bord'],
      ['API Gemini (Google)', "Service d'intelligence artificielle de l'assistant"],
      ['Outils de modélisation', 'Diagrammes UML, maquettes et diagramme de planification'],
    ], [35, 65]),

    H2('3. Implémentation de la base de données'),
    H3('3.1 Création de la base de données'),
    P("La base de données **insfp** est créée sur le serveur MySQL de Laragon ; les paramètres de connexion sont définis dans le fichier `.env` du backend :"),
    ...code(['DB_CONNECTION=mysql', 'DB_HOST=127.0.0.1', 'DB_PORT=3306', 'DB_DATABASE=insfp', 'DB_USERNAME=root', 'DB_PASSWORD=', 'SESSION_DRIVER=file'].join('\n')),
    P("Les tables sont ensuite créées par les **migrations** Laravel, et des données de démonstration peuvent être insérées par les **seeders** :"),
    ...code(['CREATE DATABASE insfp CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;', 'php artisan migrate', 'php artisan db:seed'].join('\n')),
    note("Le pilote de session est `file` : la table `sessions` de la base est déjà utilisée pour les promotions (classe TrainingSession).", 'info'),
    H3('3.2 Création des tables'),
    P("Chaque table est décrite par une migration versionnée, ce qui garantit la reproductibilité du schéma. Exemples :"),
    H4('Table users'),
    ...code([
      "Schema::create('users', function (Blueprint $table) {",
      "    $table->bigIncrements('id');",
      "    $table->string('email', 255)->unique()->nullable();",
      "    $table->string('phone', 20)->unique()->nullable();",
      "    $table->string('password', 255);",
      "    $table->enum('role', ['student', 'teacher', 'administration']);",
      "    $table->boolean('is_approved')->default(false);",
      "    $table->timestamps();",
      "});",
    ].join('\n')),
    H4('Table deliberations (contrainte d\'unicité)'),
    ...code([
      "Schema::create('deliberations', function (Blueprint $table) {",
      "    $table->bigIncrements('id');",
      "    $table->unsignedBigInteger('student_id');",
      "    $table->integer('semester');",
      "    $table->string('academic_year', 9);",
      "    $table->decimal('average', 4, 2)->nullable();",
      "    $table->enum('result', ['passed', 'failed']);",
      "    $table->text('observations')->nullable();",
      "    $table->date('deliberation_date')->nullable();",
      "    $table->foreign('student_id')->references('id')->on('students')->onDelete('cascade');",
      "    $table->unique(['student_id', 'semester', 'academic_year']);",
      "});",
    ].join('\n')),
    H4('Table session_specialties (offre de formation)'),
    ...code([
      "Schema::create('session_specialties', function (Blueprint $table) {",
      "    $table->bigIncrements('id');",
      "    $table->unsignedBigInteger('session_id');",
      "    $table->unsignedBigInteger('specialty_id');",
      "    $table->enum('study_type', ['presential', 'apprentissage', 'cours_soir']);",
      "    $table->foreign('session_id')->references('id')->on('sessions')->onDelete('cascade');",
      "    $table->foreign('specialty_id')->references('id')->on('specialties')->onDelete('restrict');",
      "    $table->unique(['session_id', 'specialty_id', 'study_type']);",
      "});",
    ].join('\n')),
    P("Au total, la base comporte une trentaine de tables métier (utilisateurs, stagiaires, enseignants, spécialités, modules, sessions, emplois du temps, présences, examens, notes, délibérations, révisions, devoirs, documents, messages, notifications…) ainsi que les tables techniques de Laravel (jetons d'accès, cache)."),

    H2("4. Présentation des interfaces de l'application"),
    P("Les captures suivantes ont été réalisées sur l'application en fonctionnement, avec des données de démonstration."),
    H3('4.1 Authentification'),
    ...cap('cap_01_connexion.png', 'Interface de connexion'),
    ...cap('cap_02_inscription.png', "Interface d'inscription en ligne"),
    H3('4.2 Interface administrateur'),
    ...cap('cap_10_admin_dashboard.png', "Tableau de bord de l'administration"),
    ...cap('cap_11_admin_stagiaires.png', 'Gestion des stagiaires'),
    ...cap('cap_12_admin_enseignants.png', 'Gestion des enseignants'),
    ...cap('cap_13_admin_specialites.png', 'Gestion des spécialités'),
    ...cap('cap_14_admin_sessions.png', 'Gestion des sessions (promotions)'),
    ...cap('cap_15_admin_numeros.png', "Génération des numéros d'inscription"),
    ...cap('cap_16_admin_edt.png', 'Emplois du temps par session et spécialité'),
    ...cap('cap_17_admin_deliberations.png', 'Délibérations'),
    H3('4.3 Interface utilisateur'),
    H4('Espace enseignant'),
    ...cap('cap_21_ens_modules.png', "Modules affectés à l'enseignant"),
    ...cap('cap_22_ens_examens.png', 'Examens et notes'),
    ...cap('cap_24_ens_edt.png', "Emploi du temps de l'enseignant"),
    H4('Espace stagiaire'),
    ...cap('cap_30_stag_dashboard.png', 'Tableau de bord du stagiaire'),
    ...cap('cap_31_stag_edt.png', 'Emploi du temps du stagiaire'),
    ...cap('cap_32_stag_examens.png', 'Résultats des examens'),
    ...cap('cap_33_stag_assiduite.png', 'Assiduité du stagiaire'),
    H3('4.4 Les contrôles'),
    P("Toutes les données sont validées **côté serveur** (classes de requêtes Laravel) ; l'interface affiche les messages d'erreur renvoyés par l'API. Principaux contrôles :"),
    ...T('Principaux contrôles de saisie', ['Donnée / action', 'Contrôle', 'Message affiché'], [
      ["Numéro d'inscription", 'Obligatoire, doit exister et ne pas être utilisé', 'Numéro invalide ou déjà utilisé'],
      ['Inscription', "Session, spécialité et mode d'étude conformes au numéro", 'Ce numéro ne correspond pas à la session ou à la spécialité choisie'],
      ['E-mail', 'Format valide, unique', 'Format email invalide / Email déjà utilisé'],
      ['Téléphone', 'Format 0[5-7] suivi de 8 chiffres, unique', 'Format téléphone invalide (ex : 0612345678)'],
      ['Mot de passe', 'Au moins 6 caractères à l\'inscription, confirmation identique', 'Mot de passe trop court / confirmation différente'],
      ['Date de naissance', 'Date antérieure à aujourd\'hui et postérieure à 1950', 'La date de naissance doit être avant aujourd\'hui'],
      ['Adresse', 'Entre 10 et 500 caractères', 'Adresse doit contenir au moins 10 caractères'],
      ['Module', 'Coefficient 0,5 à 10 ; 1 à 40 h / semaine ; code unique', 'Code module déjà utilisé'],
      ['Séance', "Heure de fin après l'heure de début ; aucun conflit", 'Conflit enseignant / Conflit emploi du temps'],
      ['Note', 'Entre 0 et 20 ; stagiaire de la spécialité et du semestre', 'Certains étudiants ne font pas partie de cet examen'],
      ['Session', 'Mois = février ou septembre ; activation après le mois de début', "Une session ne peut être ouverte qu'en février ou en septembre"],
      ['Devoir', 'Texte ou fichier obligatoire ; fichier ≤ 10 Mo', 'Veuillez fournir un texte ou un fichier'],
      ['Connexion', 'Au plus 10 tentatives par minute', 'Trop de tentatives'],
    ], [22, 43, 35]),

    H2('5. Sécurité et hébergement'),
    H3('5.1 Sécurité de la base de données (sauvegarde et restauration)'),
    H4('Mesures de sécurité de l\'application'),
    ...bullets([
      "Mots de passe **hachés** (bcrypt) ; ils ne sont jamais renvoyés par l'API.",
      "Authentification web par **cookie de session httpOnly** et protection **CSRF** ; régénération de la session à la connexion.",
      "**Contrôle d'accès** : middlewares `auth:sanctum`, `approved` (compte approuvé) et `role` (administration, enseignant, stagiaire) ; vérification que l'enseignant est affecté au module concerné.",
      "**Limitation du débit** : connexion (10 / min), inscription (3 / h), chatbot (15 / min), API (60 / min).",
      "**Validation** systématique des entrées et **neutralisation** des caractères HTML dans les noms et adresses (prévention XSS).",
      "**Transactions** pour les opérations multiples (inscription, saisie des notes, présences).",
      "Suppression des traces de débogage dans la version de production du frontend.",
    ]),
    H4('Sauvegarde et restauration'),
    P("La base de données est sauvegardée quotidiennement avec `mysqldump`, et les fichiers déposés (dossier `storage`) sont archivés avec la sauvegarde :"),
    ...code([
      '# Sauvegarde (planifiée chaque nuit)',
      'mysqldump -u root -p --single-transaction --routines insfp > sauvegarde_insfp_AAAAMMJJ.sql',
      '',
      '# Restauration',
      'mysql -u root -p insfp < sauvegarde_insfp_AAAAMMJJ.sql',
    ].join('\n')),
    ...bullets([
      "Conservation de plusieurs versions (par exemple les 7 derniers jours et une sauvegarde par mois).",
      "Copie des sauvegardes sur un support externe ou un stockage distant.",
      "Test périodique de restauration sur un serveur de test.",
    ]),
    H3("5.2 Hébergement de l'application web"),
    P("L'application n'est pas encore hébergée : elle a été développée et testée en local avec Laragon. Pour sa mise en ligne au sein de l'institut, nous proposons la démarche suivante :"),
    ...numbered([
      "**Serveur** : serveur Linux (VPS ou serveur de l'institut) avec Nginx, PHP 8.3 (PHP-FPM) et MySQL 8.",
      "**Backend** : déploiement du code Laravel, `composer install --no-dev`, configuration du fichier `.env` (APP_ENV=production, APP_DEBUG=false), `php artisan migrate --force`, mise en cache de la configuration et des routes.",
      "**Frontend** : `npm run build` ; les fichiers statiques produits sont servis par Nginx.",
      "**Nom de domaine et HTTPS** : certificat TLS (Let's Encrypt) pour chiffrer les échanges et sécuriser les cookies.",
    ], 'num4'),

    H2("6. Test et recette de l'application"),
    H3('6.1 Tests fonctionnels'),
    P("Chaque fonctionnalité est vérifiée selon un scénario, un résultat attendu et le résultat obtenu."),
    ...T('Cahier de tests fonctionnels', ['N°', 'Scénario', 'Résultat attendu', 'Résultat'], [
      ['T1', "Connexion avec des identifiants valides (chaque rôle)", "Redirection vers l'espace du rôle", '☐ Conforme'],
      ['T2', 'Connexion avec un mot de passe erroné', 'Message « identifiants incorrects »', '☐ Conforme'],
      ['T3', "Connexion d'un compte non approuvé", 'Message « en attente d\'approbation »', '☐ Conforme'],
      ['T4', "Génération d'un numéro d'inscription", 'Numéro unique au format attendu', '☐ Conforme'],
      ['T5', 'Inscription avec un numéro déjà utilisé', "Refus avec message d'erreur", '☐ Conforme'],
      ['T6', "Approbation puis connexion d'un stagiaire", 'Accès à « Compléter le profil » puis au tableau de bord', '☐ Conforme'],
      ['T7', 'Création de la prochaine session puis activation', 'Session en attente, activable au mois de début', '☐ Conforme'],
      ['T8', "Ajout d'une séance en conflit avec un enseignant", 'Refus « conflit enseignant »', '☐ Conforme'],
      ['T9', "Appel d'une séance par l'enseignant", 'Présences enregistrées et visibles par le stagiaire', '☐ Conforme'],
      ['T10', 'Saisie d\'une note de 25 / 20', 'Refus de la note', '☐ Conforme'],
      ['T11', 'Délibération d\'une spécialité', 'Moyennes pondérées et résultats proposés corrects', '☐ Conforme'],
      ['T12', "Remise d'un devoir avec fichier (≤ 10 Mo)", 'Remise enregistrée, statut « soumis »', '☐ Conforme'],
      ['T13', "Accès d'un stagiaire à une page d'administration", 'Accès refusé (403)', '☐ Conforme'],
      ['T14', 'Déconnexion', 'Session fermée, retour à la page de connexion', '☐ Conforme'],
    ], [7, 38, 37, 18], { align: [CEN, null, null, CEN] }),
    note("Cocher la colonne « Résultat » après exécution de chaque test sur la version finale.", 'todo'),
    H3('6.2 Tests de compatibilité'),
    ...T('Tests de compatibilité', ['Plateforme', 'Navigateur / système', 'Résultat'], [
      ['Ordinateur', 'Google Chrome', '☐ Conforme'],
      ['Ordinateur', 'Mozilla Firefox', '☐ Conforme'],
      ['Ordinateur', 'Microsoft Edge', '☐ Conforme'],
      ['Tablette', 'Chrome (affichage responsive)', '☐ Conforme'],
      ['Smartphone', 'Chrome Android (affichage adaptatif)', '☐ Conforme'],
    ], [25, 50, 25], { align: [null, null, CEN] }),
    H3('6.3 Recette utilisateur'),
    P("La recette consiste à faire valider l'application par les futurs utilisateurs (administration, enseignants, stagiaires) avant sa mise en service. Elle se déroule en trois étapes : présentation des fonctionnalités, utilisation guidée sur des cas réels, puis recueil des remarques et signature d'un procès-verbal de recette."),
    ...T('Procès-verbal de recette', ['Fonctionnalité', 'Validée par', 'Observations', 'Visa'], [
      ['Inscription et gestion des comptes', 'Administration', '', ''],
      ['Sessions, spécialités et emplois du temps', 'Service pédagogique', '', ''],
      ['Présences, examens et notes', 'Enseignants', '', ''],
      ['Délibérations et passage de semestre', 'Bureau des examens', '', ''],
      ['Consultation des informations', 'Stagiaires', '', ''],
    ], [35, 22, 30, 13]),

    H2('7. Conclusion'),
    P("Ce chapitre a présenté la réalisation de la plateforme : une architecture trois tiers reposant sur Laravel, Vue.js et MySQL, une base de données construite par migrations, des interfaces couvrant les trois espaces, ainsi que les mesures de sécurité, la stratégie de sauvegarde, la proposition d'hébergement et le plan de tests et de recette."),
  ];
}

function conclusion() {
  setChapter(5);
  return [
    L.section('Conclusion générale et perspectives'),
    L.H1('Conclusion générale et perspectives'),
    P("Ce projet de fin d'études nous a permis de concevoir et de réaliser une plateforme web de gestion intégrée pour l'Institut National Spécialisé de la Formation Professionnelle. En suivant une démarche structurée — étude préalable, analyse de l'existant, conception UML puis réalisation — nous avons répondu à la problématique de centralisation et de numérisation des processus de l'institut."),
    P("La solution couvre les activités essentielles : inscription en ligne et validation des comptes, gestion des sessions, des spécialités, des modules et des numéros d'inscription, emplois du temps sans conflit, assiduité, examens et notes, délibérations avec calcul automatique des moyennes, passage de semestre, devoirs, documents, messagerie et assistant intelligent."),
    P("Sur le plan technique, ce travail nous a permis de mettre en pratique des technologies actuelles : Laravel pour une API REST sécurisée, Vue.js et Tailwind CSS pour l'interface web et MySQL pour les données, dans une organisation agile SCRUM."),
    H3('Perspectives'),
    ...bullets([
      "Automatiser le **rattrapage** : identifier automatiquement, pour chaque stagiaire ajourné, les modules concernés (note inférieure à 10) et intégrer les notes de rattrapage au recalcul de la délibération.",
      "Générer automatiquement les **documents officiels** (attestations, relevés de notes, procès-verbaux) au format PDF et exporter les listes vers Excel.",
      "Développer une **application mobile** pour les stagiaires et les enseignants, avec des notifications instantanées (nouvelle note, changement d'emploi du temps, rappel de devoir).",
      "Exploiter le module d'**encadrement des projets de fin d'études** déjà prévu dans la base de données.",
      "Enrichir les **tableaux de bord** (taux de réussite, assiduité, suivi des abandons).",
    ]),
  ];
}

function bibliographie() {
  return [
    L.section('Bibliographie'),
    L.H1('Bibliographie et webographie'),
    ...numbered([
      "Documentation officielle de Laravel 12 — https://laravel.com/docs/12.x",
      "Documentation de Laravel Sanctum — https://laravel.com/docs/12.x/sanctum",
      "Documentation officielle de Vue.js 3 — https://vuejs.org/guide/",
      "Documentation de Tailwind CSS — https://tailwindcss.com/docs",
      "Documentation de Pinia — https://pinia.vuejs.org/",
      "Documentation de MySQL 8 — https://dev.mysql.com/doc/",
      "Documentation de l'API Gemini — https://ai.google.dev/",
      "K. Schwaber, J. Sutherland, *The Scrum Guide*, 2020 — https://scrumguides.org/",
      "Object Management Group, *Unified Modeling Language (UML) Specification*, version 2.5.1 — https://www.omg.org/spec/UML/",
      "P. Roques, *UML 2 par la pratique : études de cas et exercices corrigés*, Eyrolles.",
      "Documentation officielle de PHP — https://www.php.net/manual/fr/",
      "Documentation de Composer — https://getcomposer.org/doc/",
      "Documentation de Vite — https://vitejs.dev/guide/",
      "Documentation de Vue Router — https://router.vuejs.org/",
      "Documentation d'Axios — https://axios-http.com/docs/intro",
      "Documentation de Chart.js — https://www.chartjs.org/docs/",
      "MDN Web Docs (HTML, CSS, JavaScript) — https://developer.mozilla.org/fr/",
      "Documentation de Laragon — https://laragon.org/docs/",
      "Documentation de Git — https://git-scm.com/doc",
      "Documentation de Jira Software (Atlassian) — https://support.atlassian.com/jira-software-cloud/",
      "K. Schwaber, J. Sutherland, *Le Guide Scrum*, version française, 2020 — https://scrumguides.org/",
      "Plateforme nationale de la formation professionnelle — https://www.takwin.dz/",
    ], 'num5'),
  ];
}

module.exports = { chapitre4, conclusion, bibliographie };
