// Contenu — partie 2 : chapitre III (modélisation et conception du nouveau système)
const L = require('./lib');
const { P, bullets, numbered, H2, H3, H4, chapter, T, figure, setChapter, note, code } = L;
const { AlignmentType } = L.d;

const CEN = AlignmentType.CENTER;

// Description textuelle d'un cas d'utilisation
function uc(title, rows) {
  return T(`Description du cas d'utilisation « ${title} »`, ['Rubrique', 'Description'], rows, [24, 76]);
}

// Wireframe + légende de ses repères numérotés
function wf(file, caption, legend) {
  return [
    ...figure(`memoire/wireframes/${file}`, caption),
    ...bullets(legend.map((l, i) => `**(${i + 1})** ${l}`)),
  ];
}

function chapitre3() {
  setChapter(3);
  return [
    ...chapter('Chapitre III', 'Modélisation et conception du nouveau système'),

    // ------------------------------------------------------------ 1. Concepts
    H2('1. Concepts théoriques'),
    P("Cette section définit les notions techniques et métier sur lesquelles repose notre solution."),
    H3('1.1 Concepts techniques'),
    ...bullets([
      "**Système d'information (SI)** : ensemble organisé de ressources (personnes, données, procédures, matériel, logiciels) permettant de collecter, stocker, traiter et diffuser l'information d'une organisation.",
      "**Application web** : application accessible depuis un navigateur ; aucune installation n'est nécessaire côté utilisateur.",
      "**Architecture client-serveur / trois tiers** : séparation entre la couche présentation (application web), la couche métier (API) et la couche données (SGBD).",
      "**API REST** : interface qui expose des ressources par des URL et des verbes HTTP (GET, POST, PUT, DELETE) et échange des données au format JSON.",
      "**SPA (Single Page Application)** : application web chargée une seule fois, qui met à jour la page dynamiquement en appelant l'API.",
      "**Framework** : ensemble d'outils et de conventions qui structure le développement (Laravel côté serveur, Vue.js côté client).",
      "**ORM** : technique qui associe les tables de la base de données à des classes (modèles Eloquent de Laravel).",
      "**Base de données relationnelle** : données organisées en tables reliées par des clés ; nous utilisons MySQL.",
    ]),
    H3('1.2 Concepts métier'),
    ...bullets([
      "**Session (promotion)** : cohorte de stagiaires qui démarre en février ou en septembre ; sa durée est de 30 mois (cinq semestres).",
      "**Spécialité** : domaine de formation (ex. : Développement web et mobile) d'une durée exprimée en semestres, regroupant des modules.",
      "**Offre de formation** : spécialité proposée dans une session selon un type d'étude (présentiel, apprentissage, cours du soir).",
      "**Module** : unité d'enseignement d'une spécialité, rattachée à un semestre, avec un coefficient et un volume horaire hebdomadaire.",
      "**Numéro d'inscription** : identifiant unique généré par l'administration pour une session et une spécialité ; il permet au futur stagiaire de créer son compte.",
      "**Emploi du temps** : ensemble des séances hebdomadaires (module, enseignant, jour, horaire, salle) d'une spécialité, d'un semestre, d'un mode d'étude et d'un groupe.",
      "**Assiduité** : statut de présence d'un stagiaire à une séance (présent, absent, en retard, excusé).",
      "**Évaluation** : l'institut organise deux types d'évaluations, le **contrôle** et l'**examen**, auxquels s'ajoutent les devoirs.",
      "**Délibération** : décision de fin de semestre fondée sur la moyenne générale pondérée : **admis** si la moyenne est supérieure ou égale à 10 ; sinon le stagiaire passe le **rattrapage**, uniquement dans les modules dont la moyenne est inférieure à 10. Le rattrapage n'est pas un type d'évaluation.",
      "**Passage de semestre** : à l'ouverture d'une nouvelle session, chaque stagiaire admis passe au semestre suivant (ou est déclaré diplômé au dernier semestre) ; le cas d'un stagiaire ajourné est examiné par l'administration.",
    ]),

    // ------------------------------------------------------------ 2. Cahier des charges
    H2('2. Préparation du cahier des charges'),
    P("Le cahier des charges a été établi à partir de l'étude de l'existant, des entretiens avec le personnel et du diagnostic. Il distingue les besoins fonctionnels et non fonctionnels."),
    H3('2.1 Besoins fonctionnels'),
    H4('a) Authentification et comptes'),
    ...bullets([
      "Connexion par e-mail (tous les rôles) ou par numéro d'inscription (stagiaire) et mot de passe.",
      "Inscription en ligne d'un futur stagiaire à l'aide d'un numéro d'inscription pré-généré ; le compte reste « non approuvé » jusqu'à sa validation par l'administration.",
      "Complétion du profil à la première connexion (date de naissance, adresse, téléphone).",
      "Changement du mot de passe et réinitialisation par l'administration.",
    ]),
    H4('b) Espace administration'),
    ...bullets([
      "Tableau de bord et statistiques (stagiaires, enseignants, modules, spécialités, répartitions).",
      "Gestion des sessions : création du prochain créneau (février / septembre), ajout des spécialités et des types d'étude, activation et archivage.",
      "Gestion des spécialités, des modules et de l'affectation des enseignants aux modules.",
      "Génération des numéros d'inscription par session et spécialité.",
      "Gestion des stagiaires (actifs, diplômés, inscriptions en attente, approbation / rejet) et des enseignants.",
      "Élaboration des emplois du temps avec détection des conflits, puis publication.",
      "Consultation des examens et des notes, délibérations et traitement des révisions de passage.",
      "Publication de documents ciblés et envoi de messages (individuels ou diffusés).",
    ]),
    H4('c) Espace enseignant'),
    ...bullets([
      "Tableau de bord, modules affectés et listes des stagiaires, emploi du temps personnel.",
      "Dépôt de supports de cours, appel par séance et historique des présences.",
      "Création des examens (contrôle ou examen), saisie des notes et soumission à l'administration.",
      "Création des devoirs (remise en ligne ou en présentiel), consultation et notation des remises.",
      "Messagerie et documents.",
    ]),
    H4('d) Espace stagiaire'),
    ...bullets([
      "Tableau de bord, emploi du temps, cours, notes et examens, assiduité, délibérations.",
      "Consultation et remise des devoirs (texte et / ou fichier joint).",
      "Téléchargement des documents qui lui sont destinés, messagerie et profil.",
    ]),
    H4('e) Assistant intelligent'),
    ...bullets(["Chatbot public basé sur l'API Gemini pour répondre aux questions fréquentes (spécialités, inscription…)."]),
    H3('2.2 Besoins non fonctionnels'),
    ...bullets([
      "**Sécurité** : mots de passe hachés, session web par cookie httpOnly (Laravel Sanctum), protection CSRF, contrôle d'accès par rôle et par approbation (middlewares), validation des données côté serveur, limitation du nombre de requêtes (connexion, inscription, chatbot).",
      "**Performance** : API REST et interface web de type SPA ; chargements paginés des listes.",
      "**Disponibilité** : accès 24 h / 24 depuis un navigateur web.",
      "**Portabilité** : interface adaptée aux ordinateurs, aux tablettes et aux smartphones.",
      "**Ergonomie** : interface claire, responsive, thème clair / sombre, messages d'erreur explicites en français.",
      "**Maintenabilité et évolutivité** : séparation entre le serveur et l'interface, architecture MVC, migrations de base de données versionnées.",
      "**Intégrité des données** : clés étrangères, contraintes d'unicité et transactions pour les opérations multiples.",
    ]),

    // ------------------------------------------------------------ 3. Méthodologie
    H2('3. Choix de la méthodologie de gestion de projet'),
    P("Parmi les méthodes proposées (SCRUM et GANTT), nous avons choisi **la méthode agile SCRUM** : le projet comporte de nombreux modules fonctionnels qui ont été livrés progressivement et ajustés au fil des retours, ce qui correspond à un développement itératif et incrémental."),
    H3('3.1 Méthode agile SCRUM'),
    H4('1. Définition'),
    P("SCRUM est un cadre de gestion de projet agile, particulièrement adapté au développement logiciel. Il organise le travail en itérations courtes appelées **sprints**, à l'issue desquelles un incrément fonctionnel du produit est livré. Il repose sur la transparence, l'inspection et l'adaptation."),
    H4('2. Acteurs'),
    ...T('Rôles SCRUM dans notre projet', ['Rôle', 'Responsabilité', 'Dans notre projet'], [
      ['Product Owner', 'Définit et priorise les fonctionnalités (Product Backlog)', "Mme SAIGHI (encadrante), représentant l'INSFP"],
      ['Scrum Master', 'Veille au respect de la méthode et lève les obstacles', 'HAOUES Yasser'],
      ['Équipe de développement', 'Conçoit, développe et teste le produit', 'HAOUES Yasser, CHRMAT Khaled, LASSEL Abdelmalek'],
    ], [22, 43, 35]),
    H4('3. Événements'),
    ...T('Événements SCRUM', ['Événement', 'Objectif'], [
      ['Sprint', 'Itération durant laquelle un incrément utilisable est réalisé'],
      ['Sprint Planning', 'Choisir les éléments du backlog à réaliser pendant le sprint'],
      ['Daily Scrum', "Point quotidien de synchronisation de l'équipe (15 minutes)"],
      ['Sprint Review', "Présenter l'incrément au Product Owner et recueillir ses retours"],
      ['Sprint Retrospective', "Améliorer la manière de travailler de l'équipe"],
    ], [28, 72]),
    H4('4. User stories'),
    ...T('User stories principales', ['ID', 'En tant que…', 'je veux…', 'afin de…', 'Priorité'], [
      ['US1', 'administration', 'générer des numéros d\'inscription', 'permettre aux futurs stagiaires de s\'inscrire', 'Haute'],
      ['US2', 'visiteur', "m'inscrire avec mon numéro d'inscription", 'créer mon compte sans me déplacer', 'Haute'],
      ['US3', 'administration', 'approuver ou rejeter les inscriptions', 'contrôler les comptes créés', 'Haute'],
      ['US4', 'utilisateur', "me connecter à mon espace", 'accéder à mes fonctionnalités', 'Haute'],
      ['US5', 'administration', 'gérer les sessions et leurs spécialités', 'organiser les promotions', 'Haute'],
      ['US6', 'administration', "élaborer l'emploi du temps sans conflit", 'éviter les chevauchements', 'Haute'],
      ['US7', 'enseignant', "faire l'appel d'une séance", "suivre l'assiduité", 'Moyenne'],
      ['US8', 'enseignant', 'créer un examen et saisir les notes', 'évaluer les stagiaires', 'Haute'],
      ['US9', 'administration', 'délibérer à partir des moyennes calculées', 'statuer sur la réussite', 'Haute'],
      ['US10', 'stagiaire', 'consulter mon emploi du temps et mes notes', "être informé à tout moment", 'Haute'],
      ['US11', 'stagiaire', 'remettre un devoir en ligne', 'éviter les remises papier', 'Moyenne'],
      ['US12', 'administration', 'publier des documents et envoyer des messages', 'communiquer officiellement', 'Moyenne'],
      ['US13', 'visiteur', "poser une question à l'assistant", 'obtenir une réponse rapide', 'Basse'],
    ], [8, 16, 32, 32, 12]),
    H4('5. Processus'),
    P("Le Product Owner alimente le **Product Backlog** ; lors du Sprint Planning, l'équipe sélectionne les user stories du sprint (**Sprint Backlog**) et les découpe en tâches ; pendant le sprint, un Daily Scrum synchronise l'équipe ; le sprint se termine par une Sprint Review (démonstration de l'incrément) et une Sprint Retrospective."),
    H4('6. Cycle de vie'),
    ...figure('memoire/uml/scrum_cycle.png', 'Cycle de vie de la méthode SCRUM'),
    H3('3.1.1 Planifier le sprint de chaque besoin fonctionnel'),
    H4('1. Backlog des sprints'),
    P("Les sprints ci-dessous reprennent les périodes réelles du projet, établies d'après l'historique du dépôt Git (du 20 décembre 2025 au 30 septembre 2026)."),
    ...T('Backlog des sprints', ['Sprint', 'Objectif', 'User stories', 'Période'], [
      ['Sprint 1', 'Initialisation, API de base et espace stagiaire', 'US4, US10', '20/12/2025 – 26/12/2025'],
      ['Sprint 2', "Panneau d'administration", 'US1, US5, US6', '27/12/2025 – 09/01/2026'],
      ['Sprint 3', 'Inscription en ligne et révision de la base de données', 'US2, US3', '10/01/2026 – 17/02/2026'],
      ['Sprint 4', 'Emplois du temps par session', 'US6', '18/02/2026 – 06/03/2026'],
      ['Sprint 5', 'Espace enseignant et assistant intelligent', 'US7, US8, US11, US13', '07/03/2026 – 16/04/2026'],
      ['Sprint 6', 'Délibérations, passage de semestre et sécurité', 'US9, US12', '17/04/2026 – 23/07/2026'],
      ['Sprint 7', 'Tests, corrections et documentation', 'Toutes', '24/07/2026 – 30/09/2026'],
    ], [12, 45, 18, 25]),
    H4('2 et 3. Spécification des tâches et de leur durée'),
    ...T('Spécification des tâches et de leur durée', ['Sprint', 'Tâche', 'Début', 'Fin', 'Durée (j)'], [
      ['S1', 'Initialisation du dépôt, Laravel et migrations', '20/12/2025', '22/12/2025', '3'],
      ['S1', 'API REST de base et authentification', '22/12/2025', '23/12/2025', '2'],
      ['S1', 'Structure du frontend Vue.js / Tailwind', '23/12/2025', '24/12/2025', '2'],
      ['S1', 'Tableau de bord et pages du stagiaire', '25/12/2025', '26/12/2025', '2'],
      ['S2', 'Gestion des enseignants et des spécialités', '27/12/2025', '29/12/2025', '3'],
      ['S2', 'Emplois du temps (première version)', '05/01/2026', '07/01/2026', '3'],
      ['S2', "Sessions, documents et numéros d'inscription", '07/01/2026', '09/01/2026', '3'],
      ['S3', 'Révision du schéma et des migrations', '10/01/2026', '17/02/2026', '39'],
      ['S3', 'Recherche du numéro et inscription en ligne', '14/02/2026', '17/02/2026', '4'],
      ['S4', 'Emplois du temps complets par session et spécialité', '18/02/2026', '06/03/2026', '17'],
      ['S5', 'Profil, emploi du temps, devoirs et examens (enseignant)', '07/03/2026', '15/04/2026', '40'],
      ['S5', 'Assistant intelligent (API Gemini)', '15/04/2026', '16/04/2026', '2'],
      ['S6', 'Statuts des sessions et passage de semestre', '17/04/2026', '15/06/2026', '60'],
      ['S6', "Délibérations, révisions et types d'évaluations", '01/06/2026', '15/07/2026', '45'],
      ['S6', "Sécurisation (cookie httpOnly, contrôles d'accès)", '20/06/2026', '23/07/2026', '34'],
      ['S7', 'Tests fonctionnels et corrections', '24/07/2026', '31/08/2026', '39'],
      ['S7', 'Rédaction du mémoire et préparation du déploiement', '15/08/2026', '30/09/2026', '47'],
    ], [9, 49, 15, 15, 12], { align: [CEN, null, CEN, CEN, CEN] }),
    note("Les durées sont exprimées en jours calendaires ; certaines tâches se chevauchent car elles ont été menées en parallèle.", 'info'),
    H4('4. Diagramme de planification des sprints'),
    ...figure('memoire/uml/gantt_sprints.png', 'Diagramme de planification des sprints'),
    H4('5. Suivi du projet avec Jira Software'),
    P("Pour organiser et suivre le travail de l'équipe, nous avons utilisé **Jira Software** (Atlassian), l'outil de gestion de projet agile recommandé. Les étapes de mise en place sont présentées ci-dessous."),
    P("**Étape 1 — Création de l'espace de travail.** Après la connexion, la page d'accueil de Jira permet de rechercher ou de créer un espace (projet)."),
    ...figure('memoire/jira/img01.png', "Page d'accueil Jira et espace de travail", { maxW: 560 }),
    P("**Étape 2 — Choix du modèle.** Parmi les modèles proposés (Scrum, Kanban, gestion des services…), nous avons retenu le modèle **Scrum**, adapté à un développement par sprints."),
    ...figure('memoire/jira/img02.png', 'Sélection du modèle de projet dans Jira', { maxW: 560 }),
    ...figure('memoire/jira/img03.png', 'Aperçu du modèle Scrum et validation', { maxW: 560 }),
    P("**Étape 3 — Paramétrage du projet.** Le projet est nommé **« INFSP PROJET »**, avec la clé **IP** qui préfixe tous les tickets (IP-10, IP-11…), en accès privé et géré par l'équipe."),
    ...figure('memoire/jira/img04.png', 'Configuration et paramétrage du projet « INFSP PROJET »', { maxW: 560 }),
    P("**Étape 4 — Initialisation du backlog.** Jira crée l'espace **Backlog** et un premier sprint vide, prêt à recevoir les tickets."),
    ...figure('memoire/jira/img05.png', "Initialisation de l'espace Backlog et du premier sprint", { maxW: 560 }),
    P("**Étape 5 — Structuration en sprints.** Le travail est découpé en quatre sprints thématiques : *Socle technique et base de données*, *Authentification et sécurité*, *Administration et gestion des comptes* et *Interface et conception*."),
    ...figure('memoire/jira/img06.png', 'Structuration du projet en quatre sprints thématiques', { maxW: 560 }),
    P("**Étape 6 — Alimentation du backlog.** Chaque user story est saisie sous forme de ticket, puis affectée à un sprint et à un membre de l'équipe."),
    ...figure('memoire/jira/img07.png', 'Alimentation du backlog et répartition des tickets par sprint', { maxW: 560 }),
    P("**Étape 7 — Suivi de l'avancement.** La vue *Liste* regroupe tous les tickets avec leur responsable, leur priorité et leur état ; à la fin du projet, tous les tickets sont à l'état **Terminé**."),
    ...figure('memoire/jira/img08.png', "Vue globale des tickets et suivi de l'avancement", { maxW: 560 }),
    ...T('Tickets Jira par sprint', ['Sprint', 'Ticket', 'Intitulé', 'Responsable'], [
      ['Socle technique et base de données', 'IP-13', 'Initialisation du projet Laravel', 'LASSEL Abdelmalek'],
      ['', 'IP-14', 'Conception de la base de données MySQL et création des migrations et des modèles', 'CHRMAT Khaled'],
      ['', 'IP-15', 'Configuration du stockage des fichiers et des documents', 'CHRMAT Khaled'],
      ['Authentification et sécurité', 'IP-10', 'Module de connexion, déconnexion et réinitialisation du mot de passe', 'HAOUES Yasser'],
      ['', 'IP-11', 'Gestion des rôles et des autorisations : administration, enseignant et stagiaire', 'HAOUES Yasser'],
      ['', 'IP-12', 'Espace profil utilisateur et sécurisation des accès', 'HAOUES Yasser'],
      ['Administration et gestion des comptes', 'IP-19', 'Espace administration : validation et activation des nouveaux comptes', 'HAOUES Yasser'],
      ['', 'IP-20', 'Interface de gestion et de modification du profil utilisateur', 'CHRMAT Khaled'],
      ['Interface et conception', 'IP-16', 'Intégration de la mise en page principale : barre latérale, en-tête et tableau de bord', 'LASSEL Abdelmalek'],
      ['', 'IP-17', "Adaptation des formulaires et des tableaux à toutes les tailles d'écran", 'LASSEL Abdelmalek'],
      ['', 'IP-18', "Recette globale, correction des anomalies de l'interface et validation finale", 'LASSEL Abdelmalek'],
    ], [26, 10, 44, 20], { align: [null, AlignmentType.CENTER] }),

    // ------------------------------------------------------------ 4. UML
    H2('4. Le langage de modélisation UML'),
    H3('4.1 Les diagrammes UML'),
    P("UML (Unified Modeling Language) est un langage de modélisation graphique normalisé qui permet de visualiser, spécifier, construire et documenter un système logiciel. Il propose des diagrammes **structurels** (classes, objets, composants, déploiement…) et **comportementaux** (cas d'utilisation, activité, séquence, états…). Nous avons retenu :"),
    ...bullets([
      "le **diagramme de cas d'utilisation** : les fonctionnalités du système et les acteurs qui les utilisent ;",
      "le **diagramme d'activité** : l'enchaînement des actions d'un processus, réparties par acteur (couloirs) ;",
      "le **diagramme de séquence** : l'ordre chronologique des messages échangés entre les objets pour un scénario ;",
      "le **diagramme de classes** : la structure statique du système (classes, attributs, opérations, associations).",
    ]),
    H3('4.2 Identifier les acteurs'),
    ...T('Acteurs du nouveau système et leurs tâches', ['Acteur', 'Type', 'Tâches'], [
      ['Visiteur (futur stagiaire)', 'Principal', "S'inscrire en ligne avec un numéro d'inscription ; utiliser l'assistant."],
      ['Administration', 'Principal', "Gérer les sessions, spécialités, modules, numéros d'inscription, stagiaires, enseignants, emplois du temps, documents, messages ; délibérer et traiter les révisions de passage."],
      ['Enseignant', 'Principal', "Consulter ses modules et son emploi du temps, déposer des cours, faire l'appel, gérer les examens, les notes et les devoirs."],
      ['Stagiaire', 'Principal', "Consulter son emploi du temps, ses cours, notes, assiduité et délibérations ; remettre des devoirs ; télécharger des documents."],
      ['API Gemini', 'Secondaire (système)', "Fournir les réponses de l'assistant intelligent."],
    ], [24, 18, 58]),
    P("L'administration, l'enseignant et le stagiaire sont des spécialisations de l'acteur abstrait **Utilisateur authentifié**, qui regroupe les cas communs (s'authentifier, gérer son profil, consulter la messagerie et les documents)."),
    H3("4.3 Diagrammes de cas d'utilisation"),
    P("Le diagramme global présente les acteurs et les grands ensembles fonctionnels ; il est détaillé ensuite par acteur. Les relations « include » (inclusion obligatoire) et « extend » (extension optionnelle) ainsi que la généralisation des acteurs y sont représentées."),
    ...figure('memoire/uml/uc_global.png', "Diagramme de cas d'utilisation global"),
    ...figure('memoire/uml/uc_admin.png', "Diagramme de cas d'utilisation de l'administration"),
    ...figure('memoire/uml/uc_enseignant.png', "Diagramme de cas d'utilisation de l'enseignant"),
    ...figure('memoire/uml/uc_stagiaire.png', "Diagramme de cas d'utilisation du stagiaire"),
    H4("Description textuelle des principaux cas d'utilisation"),
    ...uc("S'inscrire en ligne", [
      ['Acteur', 'Visiteur (futur stagiaire)'],
      ['Objectif', "Créer un compte stagiaire à l'aide d'un numéro d'inscription"],
      ['Pré-condition', "L'administration a généré un numéro non utilisé pour la session et la spécialité"],
      ['Scénario nominal', "1. Le visiteur saisit son numéro d'inscription.\n2. Le système vérifie le numéro et affiche la session, la spécialité et les modes d'étude proposés.\n3. Le visiteur saisit ses informations et choisit un mode d'étude.\n4. Le système vérifie la cohérence session / spécialité / mode, crée le compte non approuvé et marque le numéro comme utilisé."],
      ['Scénarios alternatifs', "2a. Numéro introuvable ou déjà utilisé : message d'erreur.\n4a. Données invalides ou mode non proposé : message d'erreur."],
      ['Post-condition', "Le compte est en attente d'approbation"],
    ]),
    ...uc("S'authentifier", [
      ['Acteur', 'Utilisateur (administration, enseignant, stagiaire)'],
      ['Pré-condition', 'Le compte existe'],
      ['Scénario nominal', "1. L'utilisateur saisit son e-mail (ou son numéro d'inscription) et son mot de passe.\n2. Le système vérifie les identifiants et l'approbation du compte.\n3. Le système ouvre la session et redirige vers l'espace du rôle."],
      ['Scénarios alternatifs', "2a. Identifiants incorrects : message d'erreur.\n2b. Compte non approuvé : message « inscription en attente d'approbation ».\n3a. Stagiaire au profil incomplet : redirection vers « Compléter le profil »."],
    ]),
    ...uc("Saisir les notes d'un examen", [
      ['Acteur', 'Enseignant'],
      ['Pré-condition', "L'enseignant est affecté au module de l'examen"],
      ['Scénario nominal', "1. L'enseignant ouvre la saisie des notes d'un examen.\n2. Le système affiche les stagiaires de la spécialité et du semestre de l'examen.\n3. L'enseignant saisit les notes (sur 20).\n4. Le système enregistre les notes dans une transaction."],
      ['Scénarios alternatifs', "4a. Note hors de l'intervalle [0 ; 20] ou stagiaire non concerné : l'enregistrement est refusé."],
    ]),
    ...uc('Délibérer', [
      ['Acteur', 'Administration'],
      ['Scénario nominal', "1. L'administration choisit la session, la spécialité et, éventuellement, le semestre.\n2. Le système calcule la moyenne pondérée de chaque stagiaire et propose le résultat (admis si ≥ 10, ajourné sinon).\n3. L'administration vérifie ou ajuste la moyenne, le résultat et les observations, puis valide.\n4. Le système enregistre la délibération, consultable par le stagiaire."],
      ['Règle', 'Une seule délibération par stagiaire, semestre et année académique'],
    ]),

    H3("4.4 Diagrammes d'activité"),
    P("Les diagrammes d'activité suivants modélisent les principaux processus de la plateforme. Chaque couloir correspond à un acteur ou au système ; les décisions sont accompagnées de gardes, et les boucles repassent par un nœud de fusion."),
    ...figure('activite_1_inscription.png', "Diagramme d'activité : inscription d'un stagiaire", { maxH: 860 }),
    ...figure('activite_2_authentification.png', "Diagramme d'activité : authentification", { maxH: 860 }),
    ...figure('activite_3_session_passage_semestre.png', "Diagramme d'activité : ouverture d'une session et passage de semestre", { maxH: 860 }),
    ...figure('activite_4_examens_notes.png', "Diagramme d'activité : gestion des examens et des notes", { maxH: 860 }),
    ...figure('activite_5_deliberation.png', "Diagramme d'activité : délibération semestrielle", { maxH: 860 }),
    ...figure('activite_6_emploi_du_temps.png', "Diagramme d'activité : élaboration de l'emploi du temps", { maxH: 860 }),
    ...figure('activite_7_presence.png', "Diagramme d'activité : gestion de la présence", { maxH: 860 }),
    ...figure('activite_8_devoirs.png', "Diagramme d'activité : gestion des devoirs", { maxH: 860 }),

    H3('4.5 Diagrammes de séquence'),
    P("Les diagrammes de séquence décrivent les échanges entre l'acteur, l'interface (« boundary »), l'API Laravel (« control ») et la base de données (« entity »). Les fragments « alt », « opt » et « loop » représentent respectivement les alternatives, les options et les répétitions."),
    H4('4.5.1 Scénarios communs et visiteur'),
    ...figure('memoire/uml/seq_authentification.png', "Diagramme de séquence : authentification", { maxH: 860 }),
    ...figure('memoire/uml/seq_inscription.png', "Diagramme de séquence : inscription en ligne d'un stagiaire", { maxH: 860 }),
    ...figure('memoire/uml/seq_chatbot.png', "Diagramme de séquence : utilisation de l'assistant intelligent", { maxH: 860 }),
    H4('4.5.2 Scénarios de l\'administration'),
    ...figure('memoire/uml/seq_generer_numero.png', "Diagramme de séquence : génération d'un numéro d'inscription", { maxH: 860 }),
    ...figure('memoire/uml/seq_approbation.png', "Diagramme de séquence : approbation ou rejet d'une inscription", { maxH: 860 }),
    ...figure('memoire/uml/seq_activation_session.png', "Diagramme de séquence : activation d'une session et passage de semestre", { maxH: 860 }),
    ...figure('memoire/uml/seq_seance_edt.png', "Diagramme de séquence : ajout d'une séance à l'emploi du temps", { maxH: 860 }),
    ...figure('memoire/uml/seq_deliberation.png', "Diagramme de séquence : délibération semestrielle", { maxH: 860 }),
    ...figure('memoire/uml/seq_document.png', "Diagramme de séquence : publication d'un document", { maxH: 860 }),
    H4('4.5.3 Scénarios de l\'enseignant'),
    ...figure('memoire/uml/seq_creer_examen.png', "Diagramme de séquence : création d'un examen", { maxH: 860 }),
    ...figure('memoire/uml/seq_notes.png', "Diagramme de séquence : saisie des notes d'un examen", { maxH: 860 }),
    ...figure('memoire/uml/seq_presence.png', "Diagramme de séquence : faire l'appel d'une séance", { maxH: 860 }),
    H4('4.5.4 Scénarios du stagiaire'),
    ...figure('memoire/uml/seq_devoir.png', "Diagramme de séquence : remise d'un devoir", { maxH: 860 }),

    H3('4.6 Diagramme de classes'),
    H4('4.6.1 Dictionnaire de données'),
    ...require('./dico_mor').dictionnaire(),
    H4('4.6.2 Règles de gestion'),
    ...require('./dico_mor').regles(),
    H4('4.6.3 Diagramme de classes'),
    P("Le diagramme de classes ci-dessous présente l'ensemble des classes du système avec leurs attributs, leurs opérations et leurs associations. Les classes et les attributs sont issus du dictionnaire de données, donc des documents étudiés. Chaque classe possède un identifiant nommé d'après elle (idUtilisateur, idStagiaire, idModule…). Les clés étrangères n'y figurent pas : les liens sont exprimés par des associations et leurs multiplicités. L'utilisateur est une classe abstraite spécialisée en stagiaire, enseignant et administration ; les compositions (losange plein) indiquent les parties qui n'existent pas sans leur tout. Pour rester lisible, le diagramme est présenté sur une page au format A3."),
    { __a3: ['memoire/classes/diagramme_classes_complet.png', 'Diagramme de classes de la plateforme'] },
    ...figure('memoire/classes/diagramme_classes_enumerations.png', 'Types énumérés du diagramme de classes'),

    H3('4.7 Modèle objet relationnel'),
    H4('4.7.1 Les règles de passage du MOR'),
    ...require('./dico_mor').morRegles(),
    H4('4.7.2 Schéma du MOR'),
    ...require('./dico_mor').mor(),

    // ------------------------------------------------------------ 5. Conception de l'application
    H2("5. Conception de l'application web"),
    H3("5.1 Arborescence de l'application"),
    P("L'arborescence présente l'organisation des écrans par espace. Chaque espace est protégé par un contrôle de rôle ; les pages d'authentification sont publiques."),
    ...figure('memoire/uml/arborescence.png', "Arborescence de la plateforme"),
    H3("5.2 Les maquettes de l'application"),
    P("Les maquettes (wireframes) basse fidélité ci-dessous définissent la disposition des écrans avant le développement. Tous les écrans connectés partagent la même mise en page : une **barre latérale** de navigation (1) et une **barre supérieure** (2) contenant le changement de thème et l'utilisateur connecté. Les repères numérotés sont expliqués sous chaque maquette."),
    ...wf('wf_01_login.png', 'Maquette : connexion', ["Identifiant : e-mail ou numéro d'inscription.", 'Mot de passe.', 'Bouton de connexion.', "Lien vers l'inscription en ligne."]),
    ...wf('wf_02_inscription.png', 'Maquette : inscription en ligne', ["Numéro d'inscription remis par l'administration.", 'Session et spécialité, remplies automatiquement après vérification du numéro.', "Modes d'étude proposés pour cette offre.", 'Création du compte (en attente d\'approbation).']),
    ...wf('wf_03_profil.png', 'Maquette : complétion du profil (première connexion)', ['Date de naissance.', 'Adresse (10 caractères minimum).', 'Enregistrement et accès à l\'espace stagiaire.']),
    ...wf('wf_04_admin_dashboard.png', "Maquette : tableau de bord de l'administration", ['Barre latérale de navigation.', 'Barre supérieure (thème, utilisateur).', 'Cartes statistiques.', 'Graphiques par spécialité.', 'Aperçu des stagiaires.']),
    ...wf('wf_05_admin_stagiaires.png', 'Maquette : gestion des stagiaires', ['Barre latérale.', 'Barre supérieure.', 'Onglets : actifs, diplômés, inscriptions en attente.', 'Filtres (recherche, spécialité, semestre, groupe).', 'Liste paginée avec statut.', 'Actions : actualiser, ajouter.']),
    ...wf('wf_06_admin_sessions.png', 'Maquette : sessions (promotions)', ['Barre latérale.', 'Barre supérieure.', 'Session avec son état et ses dates.', 'Spécialités proposées par type d\'étude.', 'Actions : activer, spécialités, modifier, supprimer.', 'Création de la prochaine session et archives.']),
    ...wf('wf_07_admin_edt.png', "Maquette : élaboration de l'emploi du temps", ['Barre latérale.', 'Barre supérieure.', 'Contexte : spécialité, semestre, groupe, session, mode d\'étude.', 'Ajout d\'une séance (contrôle des conflits).', 'Séance planifiée (module, enseignant, salle).', 'Finalisation (publication).']),
    ...wf('wf_08_admin_deliberations.png', 'Maquette : délibérations', ['Barre latérale.', 'Barre supérieure.', 'Choix de la session, de la spécialité et du semestre.', 'Moyennes calculées et résultats proposés.', "Fenêtre d'enregistrement de la délibération."]),
    ...wf('wf_09_ens_examens.png', "Maquette : examens de l'enseignant", ['Barre latérale.', 'Barre supérieure.', 'Création d\'un examen.', 'Recherche et filtre par type.', 'Carte d\'examen (type, état, module, date).', 'Saisie des notes et soumission à l\'administration.']),
    ...wf('wf_10_ens_notes.png', 'Maquette : saisie des notes', ['Barre latérale.', 'Barre supérieure.', "Contexte de l'examen.", 'Note sur 20.', 'Mention calculée.', 'Enregistrement.']),
    ...wf('wf_11_ens_appel.png', "Maquette : faire l'appel", ['Barre latérale.', 'Barre supérieure.', 'Compteurs : inscrits, présents, absents.', 'Statut : présent, absent, retard, excusé.', 'Remarque facultative.', 'Enregistrement.']),
    ...wf('wf_12_stag_dashboard.png', 'Maquette : tableau de bord du stagiaire', ['Barre latérale.', 'Barre supérieure.', 'Indicateurs (modules, moyenne, séances, tâches).', 'Assiduité.', 'Prochains examens.', 'Modules du semestre.']),
    ...wf('wf_13_stag_edt.png', "Maquette : emploi du temps du stagiaire", ['Barre latérale.', 'Barre supérieure.', 'Grille hebdomadaire (samedi à jeudi).', 'Séance (module, enseignant, salle).']),
    H3('5.3 La charte graphique'),
    P("La charte graphique fixe l'identité visuelle de la plateforme : le logo, les couleurs, la typographie et le style des composants. Elle s'applique à l'ensemble de l'application web."),
    H4('5.3.1 Logo'),
    P("Le logo reprend les symboles de la formation professionnelle : la toque de diplômé, le livre ouvert, l'engrenage (métiers techniques) et un personnage en progression. Le sigle **INSFP** et la mention « Formation Professionnelle » sont accompagnés du croissant et de l'étoile du drapeau national."),
    ...figure('memoire/logo_insfp.png', 'Logo de la plateforme INSFP', { maxW: 260, maxH: 260 }),
    H4('5.3.2 Palette de couleurs'),
    P("Les couleurs principales sont tirées du logo ; elles sont complétées par des couleurs neutres et des couleurs d'état."),
    ...figure('memoire/palette_couleurs.png', 'Palette de couleurs', { maxW: 560 }),
    H4('5.3.3 Typographie et composants'),
    ...bullets([
      "**Typographie** : police sans empattement (Plus Jakarta Sans, à défaut Arial) ; titres en gras, étiquettes de formulaires en petites capitales espacées.",
      "**Composants** : cartes à bordure fine, tableaux filtrables et paginés, badges de statut colorés, fenêtres modales, notifications (toasts), indicateurs de chargement.",
      "**Icônes** : bibliothèque Heroicons (contour), utilisée de façon cohérente dans la navigation et les boutons.",
      "**Formes** : rayons de 4 à 8 px, ombres légères.",
      "**Responsive** : la barre latérale se replie sur petit écran ; un thème sombre est disponible.",
    ]),

    H2('6. Conclusion'),
    P("Ce chapitre a permis de formaliser les besoins, de planifier le projet avec SCRUM et de modéliser la solution avec UML : cas d'utilisation, activités, séquences et classes, jusqu'au modèle objet relationnel. Les maquettes et la charte graphique définissent l'apparence de l'application. Le chapitre suivant présente la réalisation de cette conception."),
  ];
}

module.exports = { chapitre3 };
